name: Website build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      commit_message: ${{ github.event.head_commit.message }}
    steps:
    - name: Checkout active branch
      uses: actions/checkout@v2
      with:
        path: 'work'
    - name: Prepare the web pages with Pandoc
      run: |
        cd ${{ github.workspace }}/work
        mkdir tmp
        make build
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref : 'gh-pages'
        path: 'gh-pages'
    - name: Copy site to gh-pages branch
      run: |
        rsync -rmcv ${{ github.workspace }}/work/  ${{ github.workspace }}/gh-pages/ \
          --exclude spec --exclude lib --exclude *.bib --exclude tmp --exclude .git \
          --exclude *.md
        rsync -cv ${{ github.workspace }}/work/tmp/ ${{ github.workspace }}/gh-pages/
    - name: Commit changes to gh-pages branch
      run: |
        cd ${{ github.workspace }}/gh-pages
        git config --local user.email "runner@github.com"
        git config --local user.name  "Automated build"
        git add .
        git commit -m "${{ env.commit_message }}" -a
    - name: Push changes to origin
      uses: ad-m/github-push-action@master
      with:
        branch: 'gh-pages'
        directory: 'gh-pages'
        github_token: ${{ secrets.GITHUB_TOKEN }}
